name: widgetbook_challenge
description: A solution for widgetbook challenge.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true